[build]
  # The command to build your Docker image and run it. We're assuming your app builds static files in the public folder.
  command = "docker build -t my-app . && docker run -p 5000:5000 my-app"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-installation"
