name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build --tag my-app .

      - name: Install Netlify CLI
        run: |
          npm install -g netlify-cli  # Install Netlify CLI without npm update

      - name: Authenticate with Netlify using access token
        run: |
          netlify auth --token ${{ secrets.NETLIFY_ACCESS_TOKEN }}

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod --dir=public
